#!/usr/bin/env bash

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source ./link${COLOR_NC}"
else

  link (){
    if [ -e $1 ]; then
      if [ -e $2 ]; then
        rm $2
      fi

      ln -s $1 $2
    fi
  }

  # bash
  link ~/Support/etc/bash_profile ~/.bash_profile
  link ~/Support/etc/bashrc ~/.bashrc
  link ~/Support/etc/bashrc_help ~/.bashrc_help

  # vim
  link ~/Support/etc/vim/vimrc ~/.vimrc
  link ~/Support/etc/vim/gvimrc ~/.gvimrc
  link ~/Support/etc/vim ~/.vim

  # git
  link ~/Support/etc/gitconfig ~/.gitconfig
  link ~/Support/etc/gitignore ~/.gitignore
  link ~/Support/etc/gitattributes ~/.gitattributes

  # misc
  link ~/Support/etc/subversion ~/.subversion
  link ~/Support/etc/autotest ~/.autotest
  link ~/Support/etc/irbrc ~/.irbrc
  link ~/Support/etc/ssh_config ~/.ssh/config

  source ~/.bash_profile

fi